-- Add performance blurb field to chef_shows table
-- This will store 1-2 sentence summaries of each chef's performance in a specific competition
-- Example: "Won Season 15 after dominating Restaurant Wars with modern Italian cuisine, winning 4 elimination challenges."

ALTER TABLE chef_shows ADD COLUMN performance_blurb TEXT 
  CHECK (performance_blurb IS NULL OR (LENGTH(performance_blurb) >= 10 AND LENGTH(performance_blurb) <= 500));

-- Create index for querying shows without performance blurbs (for backfill scripts)
CREATE INDEX idx_chef_shows_performance_missing 
  ON chef_shows(chef_id) 
  WHERE performance_blurb IS NULL;

-- Add comment to document the field's purpose
COMMENT ON COLUMN chef_shows.performance_blurb IS '1-2 sentence summary of chef performance in this competition, generated by LLM enrichment';
